import { Data } from "../interfaces";

export const ScoutingData: Data = {
    start: {
        preload: 0,
        team: 0,
        match: 0,
        position: "",
    },
    auto: {
        leave: 0,
        coral: 0,
        algae: 0,
        droppedCoral: 0,
        droppedAlgae: 0,
        l4: 0,
        l3: 0,
        l2: 0,
        l1: 0,
        processor: 0,
        barge: 0,
    },
    teleop: {
        floorPickup: 0,
        sourcePickup: 0,
        l4Scored: 0,
        l3Scored: 0,
        l2Scored: 0,
        l1scored: 0,
        l4Dropped: 0,
        l3Dropped: 0,
        l2Dropped: 0,
        l1Dropped: 0,
        processorScored: 0,
        processorDropped: 0,
        bargeScored: 0,
        bargeDropped: 0,
        algaeRemoved: 0,
        pickupLocation: "",
        isCoop: 0,
        park: 0,
        shallow: 0,
        deep: 0,
        missedClimb: 0,
        general: "",
        reason: "",
        explaination: "",
    },
}

export const resetData = () => {
    ScoutingData.start = {
        preload: 0,
        team: 0,
        match: 0,
        position: "",
    };

    ScoutingData.auto = {
        leave: 0,
        coral: 0,
        algae: 0,
        droppedCoral: 0,
        droppedAlgae: 0,
        l4: 0,
        l3: 0,
        l2: 0,
        l1: 0,
        processor: 0,
        barge: 0,
    };

    ScoutingData.teleop = {
        floorPickup: 0,
        sourcePickup: 0,
        l4Scored: 0,
        l3Scored: 0,
        l2Scored: 0,
        l1scored: 0,
        l4Dropped: 0,
        l3Dropped: 0,
        l2Dropped: 0,
        l1Dropped: 0,
        processorScored: 0,
        processorDropped: 0,
        bargeScored: 0,
        bargeDropped: 0,
        algaeRemoved: 0,
        pickupLocation: "",
        isCoop: 0,
        park: 0,
        shallow: 0,
        deep: 0,
        missedClimb: 0,
        general: "",
        reason: "",
        explaination: "",
    };
}